version: "3.8"

services:
  api:
    image: ghcr.io/danny-avila/librechat-dev:latest
    container_name: librechat
    restart: unless-stopped
    ports:
      - "3080:3080"                     # host:container (hardcoded = no empty-var bugs)
    environment:
      # App / network
      HOST: 0.0.0.0
      APP_PORT: 3080

      # Core backends
      MONGO_URI: mongodb://mongodb:27017/LibreChat
      MEILI_HOST: http://meilisearch:7700

      # RAG (optional; safe defaults)
      RAG_PORT: ${RAG_PORT:-8000}
      RAG_API_URL: http://rag_api:${RAG_PORT:-8000}

      # 🔐 Secrets (resolve from Portainer env panel at deploy time)
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - ./librechat.yaml:/app/librechat.yaml:ro   # OpenRouter-only config file
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
    depends_on:
      - mongodb
      - meilisearch
      - rag_api

  mongodb:
    image: mongo:7
    container_name: chat-mongodb
    restart: unless-stopped
    command: ["mongod","--noauth"]
    volumes:
      - ./data-node:/data/db
    # no public ports exposed

  meilisearch:
    image: getmeili/meilisearch:v1.12.3
    container_name: chat-meilisearch
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - ./meili_data_v1.12:/meili_data
    # no public ports exposed

  vectordb:
    image: ankane/pgvector:latest
    container_name: vectordb
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PGVECTOR_DB:-mydatabase}
      POSTGRES_USER: ${PGVECTOR_USER:-myuser}
      POSTGRES_PASSWORD: ${PGVECTOR_PASSWORD:-mypassword}
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    container_name: rag_api
    restart: unless-stopped
    depends_on:
      - vectordb
    environment:
      DB_HOST: vectordb
      RAG_PORT: ${RAG_PORT:-8000}

volumes:
  pgdata2:
